### ISSUE TITLE
A for_str function that accepts &str and returns &str?

### ISSUE THREAD

**Issue by seanmonstar** [inejge/env_proxy#2]
I'm working on a patch for rustup, and reqwest has better proxy support than hyper <0.11 did. One thing I've noticed is with `for_url`, it's not immediately obvious from the returned tuple whether the proxy should be spoken to with HTTP or HTTPS. The environment variables defined in curl usually include the protocol too, so it'd help to just receive the string back.

Would you be interested in accepting a PR to do this, if I submitted it?

**Comment by seanmonstar** [comment]
Oh right. It would look something like this:

```rust
pub fn for_str(s: &str) -> Option<String> {
    // ...
}
```

Or perhaps even `for_str<S: AsRef<str>>`...

**Comment by inejge** [comment]
(TL;DR: a PR would be fine.)

Yes, `for_url` effectively hardcodes the `http` scheme for client -> proxy connections, since TLS support for those has historically been patchy in browsers, so operationally not many proxy servers were configured to support them. It's a bit better now, and I agree that one should be able to specify TLS for proxy connections.

If the parameter for the new function is an unparsed URL, I'd prefer to call the function something like `for_url_str` to indicate the expected form. A generic parameter is convenient to have. If the parsing is done internally, how are the possible errors handled -- by returning `None`? (Fine by me.)

My plan for version 0.2 of this crate is to make `for_url` accept both `&Url` and `&str`/`String`, extend the returned tuple by an extensible struct with additional parameters (scheme, authentication credentials), and provide a way to construct the proxy URL. `for_url_str` could then be deprecated. Does this sound workable for your future use of `env_proxy`?

**Comment by cssivision** [comment]
i also need this feature, it seems that you guys have no time to fix this, i will fire a pr to fix this.

**Comment by cssivision** [comment]
i prefer this version, i think it is ok to return a `String`, and possible errors handled -- by returning None. 

```rust 
pub fn for_str(s: &str) -> Option<String> {
    // ...
}
```

**Comment by ordian** [comment]
I guess this issue can be closed now.

Example of using env_proxy 0.2 with reqwest:
```rust
    let client = reqwest::ClientBuilder::new()?
        .proxy(reqwest::Proxy::custom(|url| {
            env_proxy::for_url(url).to_url()
        }))
        .build()?;
```
