### ISSUE TITLE
Strictness of proxy-variables slightly too strong

### ISSUE THREAD

**Issue by kinnison** [inejge/env_proxy#5]
Hi, we use `env_proxy` in `rustup`'s `reqwest` based downloader, and since we switched our default from `cURL` to `reqwest` we've noticed that the handling of proxy environment variables has become slightly more strict.

In particular, where `cURL` will accept `http_proxy=somehost:port` because of the way `env_proxy` uses `url` to parse the envvar, only `http_proxy=http://somehost:port` is permitted.

If you look at `cURL`'s source, you can see here: https://github.com/curl/curl/blob/15401fa886b707ae2a42b95fa6cf313685306492/lib/url.c#L2509 that it defaults to `http://` if no scheme is supplied in the environment variable.

Would you accept a patch to `env_proxy` to handle this kind of situation, or should we look to resolving this within `rustup` instead?

Example bug in `rustup`: https://github.com/rust-lang/rustup.rs/issues/1688

**Comment by inejge** [comment]
Since close alignment with `curl` is a design goal of the crate, I think that relaxed proxy URL handling should be part of the crate itself. However, I'd like to keep the option of strict parsing, so a patch could encompass

* Introducing a private marker enum with "strict" and "relaxed" variants;
* Extending `ProxyUrl` with an instance of that enum as the third element;
* Constructing `ProxyUrl` with the enum defaulting to "strict";
* Adding a builder method converting a "strict" `ProxyUrl` to a "relaxed" one;
* Modifying `ProxyUrl::to_url()` to take the enum into account.

That would be fully backwards compatible. Alternatively, the default could be "relaxed", à la `curl`, but that would entail a) having a method that goes from "relaxed" to "strict", instead of vice versa, and b) bumping the crate version to 0.3.

**Comment by kinnison** [comment]
That approach sounds good, though I imagine that for most people, moving to 0.3 and being relaxed by default would be just as acceptable.

If you're also wanting to be compatible with cURL then it is worth noting that I don't think cURL uses `http_proxy` for `https` fetches.

**Comment by kinnison** [comment]
Since you have a fairly good idea of what's needed, would it make more sense for you to make the patch and then I can review it; or would you prefer that I take the time to learn your codebase and try and produce the patch?

**Comment by inejge** [comment]
I'll make the patch (a bit later, and I'll also look into `https` fetching behavior.)

**Comment by kinnison** [comment]
Fantastic, thank you very much.  I think the link to cURLs source code is close by the decision tree too (the function above maybe?)

**Comment by inejge** [comment]
OK, you can try eaf90ca63181055dc8d4f57393be5ee9ebd2e073 (0.3.0, not yet published on crates.io). It should recognize schema-less proxy URLs and skip `http_proxy` for `https` URLs.

**Comment by kinnison** [comment]
I shall try that as soon as I can (I'm at work currently but ought to be able to give it a go this afternoon)

**Comment by kinnison** [comment]
@inejge I can confirm that updating rustup to the above commit seems to behave correctly vs. cURL both for http(s)_proxy and for the more permissive parsing.

Thank you, and I look forward to being able to commit an update to 0.3.0

**Comment by inejge** [comment]
Published on crates.io, so I'm closing the issue.
